### ISSUE TITLE
I made a similar extension, how do I get the word out?

### ISSUE THREAD

**Issue by leggers** [spree-contrib/spree_vouchers#3]
I know this isn't the right place to put this, but there's no DM on GitHub so I figured I'd make an issue here. Here's my extension: https://github.com/Bombsheller/spree_gift_certificate. How can I let people know it exists? I've found the Spree website extensions list to be useless compared to browsing the /spree and /spree-contrib GitHub profiles. Should I transfer ownership to /spree or /spree-contrib? I'm a total rookie at this and nothing was said about what to do upon completion of extension creation (link here: http://guides.spreecommerce.com/developer/extensions_tutorial.html) so I apologize for my lack of tact in approaching the problem.

Thanks!

**Comment by peterberkenbosch** [comment]
Hi @leggers you can email  the user group that we have here: https://groups.google.com/forum/#!forum/spree-user to get some attention about it.
